vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        bannerImage:
            uri_prefix: /images/bannerImage
            upload_destination: '%kernel.project_dir%/public/images/bannerImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true

        whoWeAreImage:
            uri_prefix: /images/whoWeAreImage
            upload_destination: '%kernel.project_dir%/public/images/whoWeAreImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true

        productCategoryImage:
            uri_prefix: /images/productCategoryImage
            upload_destination: '%kernel.project_dir%/public/images/productCategoryImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true

        productImage:
            uri_prefix: /images/productImage
            upload_destination: '%kernel.project_dir%/public/images/productImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true

        productManual:
            uri_prefix: /images/productManual
            upload_destination: '%kernel.project_dir%/public/images/productManual'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true